//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Kartverket.Geosynkronisering
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class geosyncEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new geosyncEntities object using the connection string found in the 'geosyncEntities' section of the application configuration file.
        /// </summary>
        public geosyncEntities() : base("name=geosyncEntities", "geosyncEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new geosyncEntities object.
        /// </summary>
        public geosyncEntities(string connectionString) : base(connectionString, "geosyncEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new geosyncEntities object.
        /// </summary>
        public geosyncEntities(EntityConnection connection) : base(connection, "geosyncEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dataset> Datasets
        {
            get
            {
                if ((_Datasets == null))
                {
                    _Datasets = base.CreateObjectSet<Dataset>("Datasets");
                }
                return _Datasets;
            }
        }
        private ObjectSet<Dataset> _Datasets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ServerConfig> ServerConfigs
        {
            get
            {
                if ((_ServerConfigs == null))
                {
                    _ServerConfigs = base.CreateObjectSet<ServerConfig>("ServerConfigs");
                }
                return _ServerConfigs;
            }
        }
        private ObjectSet<ServerConfig> _ServerConfigs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Service> Services
        {
            get
            {
                if ((_Services == null))
                {
                    _Services = base.CreateObjectSet<Service>("Services");
                }
                return _Services;
            }
        }
        private ObjectSet<Service> _Services;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StoredChangelog> StoredChangelogs
        {
            get
            {
                if ((_StoredChangelogs == null))
                {
                    _StoredChangelogs = base.CreateObjectSet<StoredChangelog>("StoredChangelogs");
                }
                return _StoredChangelogs;
            }
        }
        private ObjectSet<StoredChangelog> _StoredChangelogs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Datasets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDatasets(Dataset dataset)
        {
            base.AddObject("Datasets", dataset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ServerConfigs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServerConfigs(ServerConfig serverConfig)
        {
            base.AddObject("ServerConfigs", serverConfig);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Services EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServices(Service service)
        {
            base.AddObject("Services", service);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StoredChangelogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStoredChangelogs(StoredChangelog storedChangelog)
        {
            base.AddObject("StoredChangelogs", storedChangelog);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="geosyncModel", Name="Dataset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dataset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dataset object.
        /// </summary>
        /// <param name="datasetId">Initial value of the DatasetId property.</param>
        public static Dataset CreateDataset(global::System.Int32 datasetId)
        {
            Dataset dataset = new Dataset();
            dataset.DatasetId = datasetId;
            return dataset;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DatasetId
        {
            get
            {
                return _DatasetId;
            }
            set
            {
                if (_DatasetId != value)
                {
                    OnDatasetIdChanging(value);
                    ReportPropertyChanging("DatasetId");
                    _DatasetId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DatasetId");
                    OnDatasetIdChanged();
                }
            }
        }
        private global::System.Int32 _DatasetId;
        partial void OnDatasetIdChanging(global::System.Int32 value);
        partial void OnDatasetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SchemaFileUri
        {
            get
            {
                return _SchemaFileUri;
            }
            set
            {
                OnSchemaFileUriChanging(value);
                ReportPropertyChanging("SchemaFileUri");
                _SchemaFileUri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SchemaFileUri");
                OnSchemaFileUriChanged();
            }
        }
        private global::System.String _SchemaFileUri;
        partial void OnSchemaFileUriChanging(global::System.String value);
        partial void OnSchemaFileUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DatasetProvider
        {
            get
            {
                return _DatasetProvider;
            }
            set
            {
                OnDatasetProviderChanging(value);
                ReportPropertyChanging("DatasetProvider");
                _DatasetProvider = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DatasetProvider");
                OnDatasetProviderChanged();
            }
        }
        private global::System.String _DatasetProvider;
        partial void OnDatasetProviderChanging(global::System.String value);
        partial void OnDatasetProviderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ServerMaxCount
        {
            get
            {
                return _ServerMaxCount;
            }
            set
            {
                OnServerMaxCountChanging(value);
                ReportPropertyChanging("ServerMaxCount");
                _ServerMaxCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ServerMaxCount");
                OnServerMaxCountChanged();
            }
        }
        private Nullable<global::System.Int32> _ServerMaxCount;
        partial void OnServerMaxCountChanging(Nullable<global::System.Int32> value);
        partial void OnServerMaxCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DatasetConnection
        {
            get
            {
                return _DatasetConnection;
            }
            set
            {
                OnDatasetConnectionChanging(value);
                ReportPropertyChanging("DatasetConnection");
                _DatasetConnection = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DatasetConnection");
                OnDatasetConnectionChanged();
            }
        }
        private global::System.String _DatasetConnection;
        partial void OnDatasetConnectionChanging(global::System.String value);
        partial void OnDatasetConnectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBSchema
        {
            get
            {
                return _DBSchema;
            }
            set
            {
                OnDBSchemaChanging(value);
                ReportPropertyChanging("DBSchema");
                _DBSchema = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBSchema");
                OnDBSchemaChanged();
            }
        }
        private global::System.String _DBSchema;
        partial void OnDBSchemaChanging(global::System.String value);
        partial void OnDBSchemaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransformationConnection
        {
            get
            {
                return _TransformationConnection;
            }
            set
            {
                OnTransformationConnectionChanging(value);
                ReportPropertyChanging("TransformationConnection");
                _TransformationConnection = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransformationConnection");
                OnTransformationConnectionChanged();
            }
        }
        private global::System.String _TransformationConnection;
        partial void OnTransformationConnectionChanging(global::System.String value);
        partial void OnTransformationConnectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DefaultCrs
        {
            get
            {
                return _DefaultCrs;
            }
            set
            {
                OnDefaultCrsChanging(value);
                ReportPropertyChanging("DefaultCrs");
                _DefaultCrs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DefaultCrs");
                OnDefaultCrsChanged();
            }
        }
        private global::System.String _DefaultCrs;
        partial void OnDefaultCrsChanging(global::System.String value);
        partial void OnDefaultCrsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpperCornerCoords
        {
            get
            {
                return _UpperCornerCoords;
            }
            set
            {
                OnUpperCornerCoordsChanging(value);
                ReportPropertyChanging("UpperCornerCoords");
                _UpperCornerCoords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpperCornerCoords");
                OnUpperCornerCoordsChanged();
            }
        }
        private global::System.String _UpperCornerCoords;
        partial void OnUpperCornerCoordsChanging(global::System.String value);
        partial void OnUpperCornerCoordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LowerCornerCoords
        {
            get
            {
                return _LowerCornerCoords;
            }
            set
            {
                OnLowerCornerCoordsChanging(value);
                ReportPropertyChanging("LowerCornerCoords");
                _LowerCornerCoords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LowerCornerCoords");
                OnLowerCornerCoordsChanged();
            }
        }
        private global::System.String _LowerCornerCoords;
        partial void OnLowerCornerCoordsChanging(global::System.String value);
        partial void OnLowerCornerCoordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TargetNamespace
        {
            get
            {
                return _TargetNamespace;
            }
            set
            {
                OnTargetNamespaceChanging(value);
                ReportPropertyChanging("TargetNamespace");
                _TargetNamespace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TargetNamespace");
                OnTargetNamespaceChanged();
            }
        }
        private global::System.String _TargetNamespace;
        partial void OnTargetNamespaceChanging(global::System.String value);
        partial void OnTargetNamespaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TargetNamespacePrefix
        {
            get
            {
                return _TargetNamespacePrefix;
            }
            set
            {
                OnTargetNamespacePrefixChanging(value);
                ReportPropertyChanging("TargetNamespacePrefix");
                _TargetNamespacePrefix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TargetNamespacePrefix");
                OnTargetNamespacePrefixChanged();
            }
        }
        private global::System.String _TargetNamespacePrefix;
        partial void OnTargetNamespacePrefixChanging(global::System.String value);
        partial void OnTargetNamespacePrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Decimals
        {
            get
            {
                return _Decimals;
            }
            set
            {
                OnDecimalsChanging(value);
                ReportPropertyChanging("Decimals");
                _Decimals = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Decimals");
                OnDecimalsChanged();
            }
        }
        private Nullable<global::System.Int32> _Decimals = 3;
        partial void OnDecimalsChanging(Nullable<global::System.Int32> value);
        partial void OnDecimalsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Tolerance
        {
            get
            {
                return _Tolerance;
            }
            set
            {
                OnToleranceChanging(value);
                ReportPropertyChanging("Tolerance");
                _Tolerance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tolerance");
                OnToleranceChanged();
            }
        }
        private Nullable<global::System.Int32> _Tolerance = -1;
        partial void OnToleranceChanging(Nullable<global::System.Int32> value);
        partial void OnToleranceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="geosyncModel", Name="ServerConfig")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ServerConfig : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ServerConfig object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ServerConfig CreateServerConfig(global::System.Int32 id)
        {
            ServerConfig serverConfig = new ServerConfig();
            serverConfig.ID = id;
            return serverConfig;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FTPUrl
        {
            get
            {
                return _FTPUrl;
            }
            set
            {
                OnFTPUrlChanging(value);
                ReportPropertyChanging("FTPUrl");
                _FTPUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FTPUrl");
                OnFTPUrlChanged();
            }
        }
        private global::System.String _FTPUrl;
        partial void OnFTPUrlChanging(global::System.String value);
        partial void OnFTPUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FTPUser
        {
            get
            {
                return _FTPUser;
            }
            set
            {
                OnFTPUserChanging(value);
                ReportPropertyChanging("FTPUser");
                _FTPUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FTPUser");
                OnFTPUserChanged();
            }
        }
        private global::System.String _FTPUser;
        partial void OnFTPUserChanging(global::System.String value);
        partial void OnFTPUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FTPPwd
        {
            get
            {
                return _FTPPwd;
            }
            set
            {
                OnFTPPwdChanging(value);
                ReportPropertyChanging("FTPPwd");
                _FTPPwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FTPPwd");
                OnFTPPwdChanged();
            }
        }
        private global::System.String _FTPPwd;
        partial void OnFTPPwdChanging(global::System.String value);
        partial void OnFTPPwdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="geosyncModel", Name="Service")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Service : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Service object.
        /// </summary>
        /// <param name="serviceID">Initial value of the ServiceID property.</param>
        public static Service CreateService(global::System.String serviceID)
        {
            Service service = new Service();
            service.ServiceID = serviceID;
            return service;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Abstract
        {
            get
            {
                return _Abstract;
            }
            set
            {
                OnAbstractChanging(value);
                ReportPropertyChanging("Abstract");
                _Abstract = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Abstract");
                OnAbstractChanged();
            }
        }
        private global::System.String _Abstract;
        partial void OnAbstractChanging(global::System.String value);
        partial void OnAbstractChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fees
        {
            get
            {
                return _Fees;
            }
            set
            {
                OnFeesChanging(value);
                ReportPropertyChanging("Fees");
                _Fees = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fees");
                OnFeesChanged();
            }
        }
        private global::System.String _Fees;
        partial void OnFeesChanging(global::System.String value);
        partial void OnFeesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccessConstraints
        {
            get
            {
                return _AccessConstraints;
            }
            set
            {
                OnAccessConstraintsChanging(value);
                ReportPropertyChanging("AccessConstraints");
                _AccessConstraints = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccessConstraints");
                OnAccessConstraintsChanged();
            }
        }
        private global::System.String _AccessConstraints;
        partial void OnAccessConstraintsChanging(global::System.String value);
        partial void OnAccessConstraintsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProviderName
        {
            get
            {
                return _ProviderName;
            }
            set
            {
                OnProviderNameChanging(value);
                ReportPropertyChanging("ProviderName");
                _ProviderName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProviderName");
                OnProviderNameChanged();
            }
        }
        private global::System.String _ProviderName;
        partial void OnProviderNameChanging(global::System.String value);
        partial void OnProviderNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProviderSite
        {
            get
            {
                return _ProviderSite;
            }
            set
            {
                OnProviderSiteChanging(value);
                ReportPropertyChanging("ProviderSite");
                _ProviderSite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProviderSite");
                OnProviderSiteChanged();
            }
        }
        private global::System.String _ProviderSite;
        partial void OnProviderSiteChanging(global::System.String value);
        partial void OnProviderSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IndividualName
        {
            get
            {
                return _IndividualName;
            }
            set
            {
                OnIndividualNameChanging(value);
                ReportPropertyChanging("IndividualName");
                _IndividualName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IndividualName");
                OnIndividualNameChanged();
            }
        }
        private global::System.String _IndividualName;
        partial void OnIndividualNameChanging(global::System.String value);
        partial void OnIndividualNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Facsimile
        {
            get
            {
                return _Facsimile;
            }
            set
            {
                OnFacsimileChanging(value);
                ReportPropertyChanging("Facsimile");
                _Facsimile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Facsimile");
                OnFacsimileChanged();
            }
        }
        private global::System.String _Facsimile;
        partial void OnFacsimileChanging(global::System.String value);
        partial void OnFacsimileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Deliverypoint
        {
            get
            {
                return _Deliverypoint;
            }
            set
            {
                OnDeliverypointChanging(value);
                ReportPropertyChanging("Deliverypoint");
                _Deliverypoint = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Deliverypoint");
                OnDeliverypointChanged();
            }
        }
        private global::System.String _Deliverypoint;
        partial void OnDeliverypointChanging(global::System.String value);
        partial void OnDeliverypointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OnlineResourcesUrl
        {
            get
            {
                return _OnlineResourcesUrl;
            }
            set
            {
                OnOnlineResourcesUrlChanging(value);
                ReportPropertyChanging("OnlineResourcesUrl");
                _OnlineResourcesUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OnlineResourcesUrl");
                OnOnlineResourcesUrlChanged();
            }
        }
        private global::System.String _OnlineResourcesUrl;
        partial void OnOnlineResourcesUrlChanging(global::System.String value);
        partial void OnOnlineResourcesUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoursOfService
        {
            get
            {
                return _HoursOfService;
            }
            set
            {
                OnHoursOfServiceChanging(value);
                ReportPropertyChanging("HoursOfService");
                _HoursOfService = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoursOfService");
                OnHoursOfServiceChanged();
            }
        }
        private global::System.String _HoursOfService;
        partial void OnHoursOfServiceChanging(global::System.String value);
        partial void OnHoursOfServiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactInstructions
        {
            get
            {
                return _ContactInstructions;
            }
            set
            {
                OnContactInstructionsChanging(value);
                ReportPropertyChanging("ContactInstructions");
                _ContactInstructions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactInstructions");
                OnContactInstructionsChanged();
            }
        }
        private global::System.String _ContactInstructions;
        partial void OnContactInstructionsChanging(global::System.String value);
        partial void OnContactInstructionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceURL
        {
            get
            {
                return _ServiceURL;
            }
            set
            {
                OnServiceURLChanging(value);
                ReportPropertyChanging("ServiceURL");
                _ServiceURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceURL");
                OnServiceURLChanged();
            }
        }
        private global::System.String _ServiceURL;
        partial void OnServiceURLChanging(global::System.String value);
        partial void OnServiceURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ServiceID
        {
            get
            {
                return _ServiceID;
            }
            set
            {
                if (_ServiceID != value)
                {
                    OnServiceIDChanging(value);
                    ReportPropertyChanging("ServiceID");
                    _ServiceID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ServiceID");
                    OnServiceIDChanged();
                }
            }
        }
        private global::System.String _ServiceID;
        partial void OnServiceIDChanging(global::System.String value);
        partial void OnServiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Namespace
        {
            get
            {
                return _Namespace;
            }
            set
            {
                OnNamespaceChanging(value);
                ReportPropertyChanging("Namespace");
                _Namespace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Namespace");
                OnNamespaceChanged();
            }
        }
        private global::System.String _Namespace;
        partial void OnNamespaceChanging(global::System.String value);
        partial void OnNamespaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SchemaLocation
        {
            get
            {
                return _SchemaLocation;
            }
            set
            {
                OnSchemaLocationChanging(value);
                ReportPropertyChanging("SchemaLocation");
                _SchemaLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SchemaLocation");
                OnSchemaLocationChanged();
            }
        }
        private global::System.String _SchemaLocation;
        partial void OnSchemaLocationChanging(global::System.String value);
        partial void OnSchemaLocationChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="geosyncModel", Name="StoredChangelog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StoredChangelog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StoredChangelog object.
        /// </summary>
        /// <param name="changelogId">Initial value of the ChangelogId property.</param>
        public static StoredChangelog CreateStoredChangelog(global::System.Int32 changelogId)
        {
            StoredChangelog storedChangelog = new StoredChangelog();
            storedChangelog.ChangelogId = changelogId;
            return storedChangelog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderUri
        {
            get
            {
                return _OrderUri;
            }
            set
            {
                OnOrderUriChanging(value);
                ReportPropertyChanging("OrderUri");
                _OrderUri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderUri");
                OnOrderUriChanged();
            }
        }
        private global::System.String _OrderUri;
        partial void OnOrderUriChanging(global::System.String value);
        partial void OnOrderUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StartIndex
        {
            get
            {
                return _StartIndex;
            }
            set
            {
                OnStartIndexChanging(value);
                ReportPropertyChanging("StartIndex");
                _StartIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartIndex");
                OnStartIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _StartIndex;
        partial void OnStartIndexChanging(Nullable<global::System.Int32> value);
        partial void OnStartIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DownloadUri
        {
            get
            {
                return _DownloadUri;
            }
            set
            {
                OnDownloadUriChanging(value);
                ReportPropertyChanging("DownloadUri");
                _DownloadUri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DownloadUri");
                OnDownloadUriChanged();
            }
        }
        private global::System.String _DownloadUri;
        partial void OnDownloadUriChanging(global::System.String value);
        partial void OnDownloadUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EndIndex
        {
            get
            {
                return _EndIndex;
            }
            set
            {
                OnEndIndexChanging(value);
                ReportPropertyChanging("EndIndex");
                _EndIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndIndex");
                OnEndIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _EndIndex;
        partial void OnEndIndexChanging(Nullable<global::System.Int32> value);
        partial void OnEndIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Stored
        {
            get
            {
                return _Stored;
            }
            set
            {
                OnStoredChanging(value);
                ReportPropertyChanging("Stored");
                _Stored = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stored");
                OnStoredChanged();
            }
        }
        private Nullable<global::System.Boolean> _Stored;
        partial void OnStoredChanging(Nullable<global::System.Boolean> value);
        partial void OnStoredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChangelogId
        {
            get
            {
                return _ChangelogId;
            }
            set
            {
                if (_ChangelogId != value)
                {
                    OnChangelogIdChanging(value);
                    ReportPropertyChanging("ChangelogId");
                    _ChangelogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChangelogId");
                    OnChangelogIdChanged();
                }
            }
        }
        private global::System.Int32 _ChangelogId;
        partial void OnChangelogIdChanging(global::System.Int32 value);
        partial void OnChangelogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DatasetId
        {
            get
            {
                return _DatasetId;
            }
            set
            {
                OnDatasetIdChanging(value);
                ReportPropertyChanging("DatasetId");
                _DatasetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatasetId");
                OnDatasetIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DatasetId;
        partial void OnDatasetIdChanging(Nullable<global::System.Int32> value);
        partial void OnDatasetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();

        #endregion

    
    }

    #endregion

    
}
