//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangelogManager
{
    using Dapper.Contrib.Extensions;

    public class ServerConfig
    {
        public string FTPUrl { get; set; }
        public string FTPUser { get; set; }
        public string FTPPwd { get; set; }
        [Key]
        public int ID { get; set; }
    }
}
