//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangelogManager
{
    using System;
    using System.Collections.Generic;
    using Dapper.Contrib.Extensions;

    public class StoredChangelog
    {
        public string Name { get; set; }
        public string OrderUri { get; set; }
        public Nullable<int> StartIndex { get; set; }
        public string DownloadUri { get; set; }
        public Nullable<int> EndIndex { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Stored { get; set; }
        [Key]
        public int ChangelogId { get; set; }
        public Nullable<int> DatasetId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
