//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartverket.Geosynkronisering.Subscriber.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Subscriber : global::System.Configuration.ApplicationSettingsBase {
        
        private static Subscriber defaultInstance = ((Subscriber)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Subscriber())));
        
        public static Subscriber Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultDatasetId {
            get {
                return ((int)(this["DefaultDatasetId"]));
            }
            set {
                this["DefaultDatasetId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://geosynk.nois.no/tilbyder/")]
        public string DefaultServerURL {
            get {
                return ((string)(this["DefaultServerURL"]));
            }
            set {
                this["DefaultServerURL"] = value;
            }
        }
    }
}
